"""empty message

Revision ID: 5db8f223e74e
Revises: a73f4c55ba16
Create Date: 2020-03-03 18:06:48.049822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5db8f223e74e'
down_revision = 'a73f4c55ba16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
    op.execute('''
        UPDATE todos
           SET completed = False
         WHERE completed IS NULL;
    ''')
    op.alter_column('todos', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
